<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Tell</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Superpower" Version="3.2.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\superpower\lib\Tell.Superpower.csproj" />
  </ItemGroup>

</Project>
