<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Tell.Recipe.Runner.Playground</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Versions\**\*.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.0" />
    <PackageReference Include="MSTest" Version="3.9.1" />
    <PackageReference Include="NiceShell.Cli" Version="2026.108.104.12" />
    <PackageReference Include="NiceShell.Logger" Version="2026.108.101.5" />
    <PackageReference Include="Shouldly" Version="4.3.0" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Microsoft.VisualStudio.TestTools.UnitTesting" />
    <Using Include="Shouldly" />
    <Using Include="System.CommandLine" />
    <Using Include="NiceShell" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\lib\Tell.Recipe.Runner.csproj" />
  </ItemGroup>

</Project>
