<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\..\recipe\runner\lib\Tell.Recipe.Runner.csproj" />
    <ProjectReference Include="..\..\parser\lib\Tell.Rule.Parser.csproj" />
    <ProjectReference Include="..\..\..\var\use\runner\lib\Tell.Var.Use.Runner.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Tell</RootNamespace>
  </PropertyGroup>

</Project>
