name: Tell.Cli NuGet
on:
  push:
    paths:
      # - 'combo/cli/**'
      - '**' # for now combo has transient dependencies on makefile, var and superpower.
      - '.github/workflows/distro-cli-nuget.yml'
  workflow_dispatch:

jobs:
  publish:
    name: Pack & Publish nuget
    runs-on: ubuntu-latest
    steps:
      - uses: astorDev/versy/calver/nuget@main
        with:
          project: distro/cli/Tell.Cli
          nuget-api-key: ${{ secrets.NUGET_API_KEY }}